import type { Client } from './types';
import { subDays, addDays, format } from 'date-fns';

const today = new Date();

export const DUMMY_CLIENTS: Client[] = [
  {
    id: 'CLI001',
    name: 'John Doe',
    address: '123 Maple Street, Springfield',
    coordinates: { lat: 34.0522, lng: -118.2437 },
    collectionStatus: 'active',
    paymentStatus: 'paid',
    garbageStatus: 'collected',
    nextCollectionDate: format(addDays(today, 6), 'yyyy-MM-dd'),
    nextPaymentDueDate: format(addDays(today, 25), 'yyyy-MM-dd'),
    balance: 0,
    paymentHistory: [
      { id: 'PAY001', date: format(subDays(today, 30), 'yyyy-MM-dd'), amount: 25, status: 'paid' },
      { id: 'PAY002', date: format(subDays(today, 60), 'yyyy-MM-dd'), amount: 25, status: 'paid' },
    ],
  },
  {
    id: 'CLI002',
    name: 'Jane Smith',
    address: '456 Oak Avenue, Springfield',
    coordinates: { lat: 34.055, lng: -118.245 },
    collectionStatus: 'active',
    paymentStatus: 'due',
    garbageStatus: 'out',
    nextCollectionDate: format(addDays(today, 2), 'yyyy-MM-dd'),
    nextPaymentDueDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    balance: 25,
    paymentHistory: [
      { id: 'PAY003', date: format(subDays(today, 35), 'yyyy-MM-dd'), amount: 25, status: 'paid' },
    ],
  },
  {
    id: 'CLI003',
    name: 'Bob Johnson',
    address: '789 Pine Lane, Springfield',
    coordinates: { lat: 34.05, lng: -118.25 },
    collectionStatus: 'active',
    paymentStatus: 'overdue',
    garbageStatus: 'pending',
    nextCollectionDate: format(addDays(today, 2), 'yyyy-MM-dd'),
    nextPaymentDueDate: format(subDays(today, 10), 'yyyy-MM-dd'),
    balance: 50,
    paymentHistory: [],
  },
  {
    id: 'CLI004',
    name: 'Alice Williams',
    address: '101 Elm Court, Springfield',
    coordinates: { lat: 34.048, lng: -118.24 },
    collectionStatus: 'suspended',
    paymentStatus: 'overdue',
    garbageStatus: 'missed',
    nextCollectionDate: 'N/A',
    nextPaymentDueDate: format(subDays(today, 40), 'yyyy-MM-dd'),
    balance: 75,
    paymentHistory: [],
  },
  {
    id: 'CLI005',
    name: 'Charlie Brown',
    address: '212 Birch Road, Springfield',
    coordinates: { lat: 34.058, lng: -118.255 },
    collectionStatus: 'active',
    paymentStatus: 'paid',
    garbageStatus: 'not-out',
    nextCollectionDate: format(addDays(today, 4), 'yyyy-MM-dd'),
    nextPaymentDueDate: format(addDays(today, 20), 'yyyy-MM-dd'),
    balance: 0,
    paymentHistory: [
      { id: 'PAY004', date: format(subDays(today, 28), 'yyyy-MM-dd'), amount: 25, status: 'paid' },
    ],
  },
  {
    id: 'CLI006',
    name: 'Diana Prince',
    address: '333 Cedar Blvd, Springfield',
    coordinates: { lat: 34.06, lng: -118.248 },
    collectionStatus: 'active',
    paymentStatus: 'paid',
    garbageStatus: 'collected',
    nextCollectionDate: format(addDays(today, 5), 'yyyy-MM-dd'),
    nextPaymentDueDate: format(addDays(today, 18), 'yyyy-MM-dd'),
    balance: 0,
    paymentHistory: [
      { id: 'PAY005', date: format(subDays(today, 25), 'yyyy-MM-dd'), amount: 25, status: 'paid' },
    ],
  },
];
