
"use client";

import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'EN' | 'PT';

const translations = {
    EN: {
        // General
        login: 'Login',
        logout: 'Logout',
        sign_up: 'Sign Up',
        dashboard: 'Dashboard',
        email: 'Email',
        password: 'Password',
        status: 'Status',
        action: 'Action',
        cancel: 'Cancel',
        save_changes: 'Save Changes',
        close: 'Close',
        none: 'None',

        // Statuses
        active: 'Active',
        suspended: 'Suspended',
        paid: 'Paid',
        due: 'Due',
        overdue: 'Overdue',
        collected: 'Collected',
        pending: 'Pending',
        missed: 'Missed',
        'not-out': 'Not Out',
        'in-use': 'In Use',
        maintenance: 'Maintenance',
        available: 'Available',
        working: 'Working',
        'on-leave': 'On Leave',
        completed: 'Completed',

        // Landing Page
        welcome_to_recolixo: 'Welcome to RECOLIXO',
        modern_solution_for_waste_management: 'The modern solution for waste management.',
        service_providers: 'Service Providers',
        manage_clients_routes_and_payments: 'Manage clients, routes, and payments.',
        provider_description: 'Access your dashboard to track collections, view client information on an interactive map, and manage financials.',
        go_to_provider_dashboard: 'Go to Provider Dashboard',
        clients: 'Clients',
        track_collections_and_manage_payments: 'Track collections and manage payments.',
        client_description: 'View your collection schedule, report your garbage status, track your service in real-time, and handle payments easily.',
        go_to_client_dashboard: 'Go to Client Dashboard',

        // Login Page
        login_to_recolixo: 'Login to RECOLIXO',
        enter_credentials: 'Enter your credentials to access your account.',
        logging_in: 'Logging in...',
        dont_have_account: "Don't have an account?",
        login_successful: 'Login Successful',
        redirecting_to_dashboard: 'Redirecting to your dashboard...',
        
        // Signup Page
        create_account: 'Create an Account',
        join_recolixo: "Join RECOLIXO today. It's quick and easy.",
        full_name: 'Full Name',
        i_am_a: 'I am a...',
        client_radio: 'Client (I need garbage collection)',
        provider_radio: 'Service Provider (I offer collection services)',
        creating_account: 'Creating Account...',
        already_have_account: 'Already have an account?',
        account_created: 'Account Created!',
        redirecting_to_login: 'You have successfully signed up. Redirecting to login...',

        // Provider Layout
        collection_map: 'Collection Map',
        payments: 'Payments',
        fleet: 'Fleet',
        workforce: 'Workforce',
        subscription: 'Subscription',
        home_page: 'Home Page',
        provider_dashboard: 'Provider Dashboard',
        
        // Client Layout
        make_payment: 'Make a Payment',
        hello: 'Hello',
        client_dashboard_subtitle: 'Here is a summary of your RECOLIXO service.',
        service_status: 'Service Status',
        next_collection_date: 'Next Collection Date',
        collection_status_label: 'Collection Status',
        next_payment_due: 'Next Payment Due',
        current_balance: 'Current Balance',
        payment_history: 'Payment History',
        payment_history_description: 'A record of your recent payments.',
        date: 'Date',
        amount: 'Amount',
        no_payment_history: 'No payment history found.',
        garbage_for_collection_title: 'Garbage for Collection?',
        garbage_for_collection_subtitle: 'Let us know if you have garbage ready for the next scheduled pickup.',
        garbage_status_yes: 'Yes, I have garbage out',
        garbage_status_no: 'No garbage this time',
        garbage_status_footer: 'Toggling this helps us optimize routes and save fuel. Thank you!',
        status_updated: 'Status Updated',
        garbage_status_yes_toast: "We've been notified that you have garbage for collection.",
        garbage_status_no_toast: "We've been notified that you do not have garbage for collection.",
        location_sharing_title: 'Location Sharing',
        location_sharing_subtitle: 'Allow your provider to see your location for optimized routing.',
        share_my_location: 'Share My Location',
        share_my_location_subtitle: 'Help us create efficient collection routes.',
        location_preference_updated: 'Location Preference Updated',
        location_sharing_on_toast: 'You are now sharing your location with the provider.',
        location_sharing_off_toast: 'You are now not sharing your location with the provider.',
        make_a_payment_title: 'Make a Payment',
        make_a_payment_subtitle: 'Securely pay your bill or add credit to your account.',
        payment_details: 'Payment Details',
        payment_details_desc_1: 'Enter your payment information below. Your current balance is',
        payment_amount_mt: 'Payment Amount (MT)',
        cardholder_name: 'Cardholder Name',
        card_number: 'Card Number',
        expiry_date: 'Expiry Date',
        cvc: 'CVC',
        processing: 'Processing...',
        pay_now: 'Pay Now',
        payment_successful_title: 'Payment Successful',
        payment_successful_desc: 'Your payment of',

        // Provider Dashboard
        trial_period_message: 'You are currently on the free trial period.',
        view_subscription_plans: 'View subscription plans.',
        subscribe_now: 'Subscribe Now',
        total_clients: 'Total Clients',
        active_collections_today: 'Active Collections Today',
        clients_with_issues: 'Clients with Issues',
        client_management_title: 'Client Management',
        client_management_subtitle: 'View, filter, and manage your clients.',
        search_by_name_or_address: 'Search by name or address...',
        collection_status: 'Collection Status',
        all_collection_status: 'All Collection Status',
        payment_status: 'Payment Status',
        all_payment_status: 'All Payment Status',
        balance: 'Balance',
        no_clients_match_filters: 'No clients match the current filters.',
        
        // Provider Map
        map_title: 'Interactive Collection Map',
        map_subtitle: 'Visualize client locations and routes.',
        my_location: 'My Location',
        alert_location_error: 'Could not get your location. Please ensure you have enabled location services.',
        alert_geolocation_not_supported: 'Geolocation is not supported by this browser.',
        client_status_set_to: "Client's status set to",
        update_status: 'Update Status',
        update_status_desc_1: 'Change garbage status for',
        route_manager_title: 'Route Manager',
        route_manager_subtitle: 'Define and manage collection routes.',
        create_new_route: 'Create New Route',
        edit_route: 'Edit Route',
        no_routes_created: 'No routes created yet.',

        // Provider Fleet
        fleet_management_title: 'Fleet Management',
        fleet_management_subtitle: 'Register, track, and manage your fleet of collection vehicles.',
        fuel_type: 'Fuel Type',
        capacity: 'Capacity',
        next_maintenance: 'Next Maintenance',
        view_details: 'View Details',
        vehicle_details_title: 'Vehicle Details',
        vehicle_details_desc: 'Complete information for',
        license_plate: 'License Plate',
        type: 'Type',
        update_status_title: 'Update Status',
        update_status_desc: 'Change the availability status for this vehicle.',
        select_status: 'Select status',

        // Provider Workforce
        workforce_management_title: 'Workforce Management',
        workforce_management_subtitle: 'Manage your drivers, pickers, and other operational staff.',
        active_assignments_title: 'Active Assignments',
        active_assignments_subtitle: 'A list of tasks currently being performed by your workforce.',
        worker: 'Worker',
        vehicle: 'Vehicle',
        task: 'Task',
        mark_as_complete: 'Mark as Complete',
        no_active_assignments: 'No active assignments.',
        assignment_completed_title: 'Assignment Completed',
        assignment_completed_desc: 'The task has been marked as complete.',
        Driver: 'Driver',
        Picker: 'Picker',
        Supervisor: 'Supervisor',
        employment: 'Employment',
        permanent: 'Permanent',
        occasional: 'Occasional',
        wage: 'Wage',
        hour: 'hour',
        last_check_in: 'Last Check-in',
        assigned_vehicle: 'Assigned Vehicle',
        view_timesheet: 'View Timesheet',
        assign_task: 'Assign Task',
        timesheet_for: 'Timesheet for',
        timesheet_desc: 'Recent check-in and check-out times for the current month.',
        check_in: 'Check In',
        check_out: 'Check Out',
        total_hours: 'Total Hours',
        no_timesheet_entries: 'No timesheet entries found.',
        total_monthly_hours: 'Total Monthly Hours',
        assign_task_to: 'Assign Task to',
        assign_task_desc: 'Assign a vehicle for the current shift.',
        assign_vehicle: 'Assign Vehicle',
        select_a_vehicle: 'Select a vehicle',
        save_assignment: 'Save Assignment',

        // Provider Payments
        payments_reporting_title: 'Payments & Reporting',
        payments_reporting_subtitle: 'Track client payments, view balances, and generate financial reports.',
        client_payment_status_title: 'Client Payment Status',
        client_payment_status_subtitle: 'Detailed overview of all client payments and balances.',
        client: 'Client',
        next_due_date: 'Next Due Date',
        revenue_overview: 'Revenue Overview',
        revenue_overview_subtitle: 'Monthly revenue from paid invoices.',
        total: 'Total',
        total_outstanding_balance: 'Total Outstanding Balance',
        total_outstanding_balance_subtitle: 'Across all clients with due or overdue payments.',

        // Provider Subscription
        subscription_page_title: 'Our Subscription Plans',
        subscription_page_subtitle: "Choose the plan that's right for your business.",
        per_month: '/month',
        plan_pratico_description: 'Ideal for getting started and managing essential client information.',
        plan_pratico_feature1: 'Client Information Dashboard',
        plan_pratico_feature2: 'Payment Tracking',
        plan_gestao_description: 'Perfect for optimizing routes and visualizing your operations.',
        plan_gestao_feature1: 'All features from Prático',
        plan_gestao_feature2: 'Interactive Collection Map',
        plan_gestao_feature3: 'Route Management',
        plan_total_description: 'The complete solution for managing your entire waste collection business.',
        plan_total_feature1: 'All features from Gestão',
        plan_total_feature2: 'Fleet Management',
        plan_total_feature3: 'Workforce Management',
        plan_total_feature4: 'Advanced Reporting',

        // Weekdays
        Monday: 'Monday',
        Tuesday: 'Tuesday',
        Wednesday: 'Wednesday',
        Thursday: 'Thursday',
        Friday: 'Friday',
        Saturday: 'Saturday',
        Sunday: 'Sunday',
    },
    PT: {
        // General
        login: 'Entrar',
        logout: 'Sair',
        sign_up: 'Registar',
        dashboard: 'Painel de Controlo',
        email: 'Email',
        password: 'Palavra-passe',
        status: 'Estado',
        action: 'Ação',
        cancel: 'Cancelar',
        save_changes: 'Guardar Alterações',
        close: 'Fechar',
        none: 'Nenhum',

        // Statuses
        active: 'Ativo',
        suspended: 'Suspenso',
        paid: 'Pago',
        due: 'Pendente',
        overdue: 'Atrasado',
        collected: 'Recolhido',
        pending: 'Pendente',
        missed: 'Falhado',
        'not-out': 'Não Exposto',
        'in-use': 'Em Uso',
        maintenance: 'Manutenção',
        available: 'Disponível',
        working: 'A trabalhar',
        'on-leave': 'De licença',
        completed: 'Concluído',

        // Landing Page
        welcome_to_recolixo: 'Bem-vindo à RECOLIXO',
        modern_solution_for_waste_management: 'A solução moderna para a gestão de resíduos.',
        service_providers: 'Provedores de Serviço',
        manage_clients_routes_and_payments: 'Faça a gestão de clientes, rotas e pagamentos.',
        provider_description: 'Aceda ao seu painel para rastrear coletas, visualizar informações de clientes num mapa interativo e gerir as finanças.',
        go_to_provider_dashboard: 'Ir para o Painel do Provedor',
        clients: 'Clientes',
        track_collections_and_manage_payments: 'Acompanhe as coletas e faça a gestão de pagamentos.',
        client_description: 'Veja o seu calendário de coletas, reporte o estado do seu lixo, acompanhe o serviço em tempo real e trate dos pagamentos facilmente.',
        go_to_client_dashboard: 'Ir para o Painel do Cliente',
        
        // Login Page
        login_to_recolixo: 'Entrar na RECOLIXO',
        enter_credentials: 'Insira as suas credenciais para aceder à sua conta.',
        logging_in: 'A entrar...',
        dont_have_account: 'Não tem uma conta?',
        login_successful: 'Login com sucesso',
        redirecting_to_dashboard: 'A redirecionar para o seu painel...',

        // Signup Page
        create_account: 'Criar uma Conta',
        join_recolixo: 'Junte-se à RECOLIXO hoje. É rápido e fácil.',
        full_name: 'Nome Completo',
        i_am_a: 'Eu sou...',
        client_radio: 'Cliente (preciso de coleta de lixo)',
        provider_radio: 'Provedor de Serviço (ofereço serviços de coleta)',
        creating_account: 'A criar conta...',
        already_have_account: 'Já tem uma conta?',
        account_created: 'Conta Criada!',
        redirecting_to_login: 'Registou-se com sucesso. A redirecionar para o login...',

        // Provider Layout
        collection_map: 'Mapa de Coleta',
        payments: 'Pagamentos',
        fleet: 'Frota',
        workforce: 'Força de Trabalho',
        subscription: 'Subscrição',
        home_page: 'Página Inicial',
        provider_dashboard: 'Painel do Provedor',
        
        // Client Layout
        make_payment: 'Fazer um Pagamento',
        hello: 'Olá',
        client_dashboard_subtitle: 'Aqui está um resumo do seu serviço RECOLIXO.',
        service_status: 'Estado do Serviço',
        next_collection_date: 'Próxima Data de Coleta',
        collection_status_label: 'Estado da Coleta',
        next_payment_due: 'Próximo Pagamento',
        current_balance: 'Saldo Atual',
        payment_history: 'Histórico de Pagamentos',
        payment_history_description: 'Um registo dos seus pagamentos recentes.',
        date: 'Data',
        amount: 'Valor',
        no_payment_history: 'Nenhum histórico de pagamento encontrado.',
        garbage_for_collection_title: 'Lixo para Coleta?',
        garbage_for_collection_subtitle: 'Informe-nos se tem lixo pronto para a próxima coleta agendada.',
        garbage_status_yes: 'Sim, tenho lixo exposto',
        garbage_status_no: 'Sem lixo desta vez',
        garbage_status_footer: 'Alternar esta opção ajuda-nos a otimizar rotas e poupar combustível. Obrigado!',
        status_updated: 'Estado Atualizado',
        garbage_status_yes_toast: 'Fomos notificados de que tem lixo para coleta.',
        garbage_status_no_toast: 'Fomos notificados de que não tem lixo para coleta.',
        location_sharing_title: 'Partilha de Localização',
        location_sharing_subtitle: 'Permita que o seu provedor veja a sua localização para otimização de rotas.',
        share_my_location: 'Partilhar a Minha Localização',
        share_my_location_subtitle: 'Ajude-nos a criar rotas de coleta eficientes.',
        location_preference_updated: 'Preferência de Localização Atualizada',
        location_sharing_on_toast: 'Está agora a partilhar a sua localização com o provedor.',
        location_sharing_off_toast: 'Deixou de partilhar a sua localização com o provedor.',
        make_a_payment_title: 'Fazer um Pagamento',
        make_a_payment_subtitle: 'Pague a sua fatura de forma segura ou adicione crédito à sua conta.',
        payment_details: 'Detalhes de Pagamento',
        payment_details_desc_1: 'Insira as suas informações de pagamento abaixo. O seu saldo atual é de',
        payment_amount_mt: 'Valor do Pagamento (MT)',
        cardholder_name: 'Nome do Titular do Cartão',
        card_number: 'Número do Cartão',
        expiry_date: 'Data de Validade',
        cvc: 'CVC',
        processing: 'A processar...',
        pay_now: 'Pagar Agora',
        payment_successful_title: 'Pagamento com Sucesso',
        payment_successful_desc: 'O seu pagamento de',

        // Provider Dashboard
        trial_period_message: 'Está atualmente no período de teste gratuito.',
        view_subscription_plans: 'Ver planos de subscrição.',
        subscribe_now: 'Subscrever Agora',
        total_clients: 'Total de Clientes',
        active_collections_today: 'Coletas Ativas Hoje',
        clients_with_issues: 'Clientes com Problemas',
        client_management_title: 'Gestão de Clientes',
        client_management_subtitle: 'Veja, filtre e faça a gestão dos seus clientes.',
        search_by_name_or_address: 'Pesquisar por nome ou endereço...',
        collection_status: 'Estado da Coleta',
        all_collection_status: 'Todos os Estados de Coleta',
        payment_status: 'Estado do Pagamento',
        all_payment_status: 'Todos os Estados de Pagamento',
        balance: 'Saldo',
        no_clients_match_filters: 'Nenhum cliente corresponde aos filtros atuais.',

        // Provider Map
        map_title: 'Mapa Interativo de Coleta',
        map_subtitle: 'Visualize a localização dos clientes e as rotas.',
        my_location: 'A Minha Localização',
        alert_location_error: 'Não foi possível obter a sua localização. Por favor, certifique-se de que ativou os serviços de localização.',
        alert_geolocation_not_supported: 'A geolocalização não é suportada por este navegador.',
        client_status_set_to: "O estado do cliente foi definido para",
        update_status: 'Atualizar Estado',
        update_status_desc_1: 'Alterar o estado do lixo para',
        route_manager_title: 'Gestor de Rotas',
        route_manager_subtitle: 'Defina e faça a gestão das rotas de coleta.',
        create_new_route: 'Criar Nova Rota',
        edit_route: 'Editar Rota',
        no_routes_created: 'Nenhuma rota criada ainda.',

        // Provider Fleet
        fleet_management_title: 'Gestão de Frota',
        fleet_management_subtitle: 'Registe, acompanhe e faça a gestão da sua frota de veículos de coleta.',
        fuel_type: 'Tipo de Combustível',
        capacity: 'Capacidade',
        next_maintenance: 'Próxima Manutenção',
        view_details: 'Ver Detalhes',
        vehicle_details_title: 'Detalhes do Veículo',
        vehicle_details_desc: 'Informação completa para',
        license_plate: 'Matrícula',
        type: 'Tipo',
        update_status_title: 'Atualizar Estado',
        update_status_desc: 'Alterar o estado de disponibilidade deste veículo.',
        select_status: 'Selecione o estado',

        // Provider Workforce
        workforce_management_title: 'Gestão da Força de Trabalho',
        workforce_management_subtitle: 'Faça a gestão dos seus motoristas, coletores e outro pessoal operacional.',
        active_assignments_title: 'Tarefas Ativas',
        active_assignments_subtitle: 'Uma lista de tarefas atualmente a ser executadas pela sua força de trabalho.',
        worker: 'Trabalhador',
        vehicle: 'Veículo',
        task: 'Tarefa',
        mark_as_complete: 'Marcar como Concluída',
        no_active_assignments: 'Nenhuma tarefa ativa.',
        assignment_completed_title: 'Tarefa Concluída',
        assignment_completed_desc: 'A tarefa foi marcada como concluída.',
        Driver: 'Motorista',
        Picker: 'Coletor',
        Supervisor: 'Supervisor',
        employment: 'Emprego',
        permanent: 'Permanente',
        occasional: 'Ocasional',
        wage: 'Salário',
        hour: 'hora',
        last_check_in: 'Último Check-in',
        assigned_vehicle: 'Veículo Atribuído',
        view_timesheet: 'Ver Folha de Horas',
        assign_task: 'Atribuir Tarefa',
        timesheet_for: 'Folha de Horas para',
        timesheet_desc: 'Horas de check-in e check-out recentes para o mês atual.',
        check_in: 'Check In',
        check_out: 'Check Out',
        total_hours: 'Total de Horas',
        no_timesheet_entries: 'Nenhuma entrada na folha de horas encontrada.',
        total_monthly_hours: 'Total de Horas Mensais',
        assign_task_to: 'Atribuir Tarefa a',
        assign_task_desc: 'Atribuir um veículo para o turno atual.',
        assign_vehicle: 'Atribuir Veículo',
        select_a_vehicle: 'Selecione um veículo',
        save_assignment: 'Guardar Atribuição',

        // Provider Payments
        payments_reporting_title: 'Pagamentos e Relatórios',
        payments_reporting_subtitle: 'Acompanhe os pagamentos dos clientes, veja os saldos e gere relatórios financeiros.',
        client_payment_status_title: 'Estado de Pagamento do Cliente',
        client_payment_status_subtitle: 'Visão detalhada de todos os pagamentos e saldos dos clientes.',
        client: 'Cliente',
        next_due_date: 'Próxima Data de Vencimento',
        revenue_overview: 'Visão Geral das Receitas',
        revenue_overview_subtitle: 'Receitas mensais de faturas pagas.',
        total: 'Total',
        total_outstanding_balance: 'Saldo Total em Dívida',
        total_outstanding_balance_subtitle: 'De todos os clientes com pagamentos pendentes ou em atraso.',

        // Provider Subscription
        subscription_page_title: 'Os Nossos Planos de Subscrição',
        subscription_page_subtitle: 'Escolha o plano certo para o seu negócio.',
        per_month: '/mês',
        plan_pratico_description: 'Ideal para começar e gerir informações essenciais dos clientes.',
        plan_pratico_feature1: 'Painel de Informações do Cliente',
        plan_pratico_feature2: 'Acompanhamento de Pagamentos',
        plan_gestao_description: 'Perfeito para otimizar rotas e visualizar as suas operações.',
        plan_gestao_feature1: 'Todas as funcionalidades do Prático',
        plan_gestao_feature2: 'Mapa de Coleta Interativo',
        plan_gestao_feature3: 'Gestão de Rotas',
        plan_total_description: 'A solução completa para gerir todo o seu negócio de coleta de resíduos.',
        plan_total_feature1: 'Todas as funcionalidades do Gestão',
        plan_total_feature2: 'Gestão de Frota',
        plan_total_feature3: 'Gestão da Força de Trabalho',
        plan_total_feature4: 'Relatórios Avançados',

        // Weekdays
        Monday: 'Segunda-feira',
        Tuesday: 'Terça-feira',
        Wednesday: 'Quarta-feira',
        Thursday: 'Quinta-feira',
        Friday: 'Sexta-feira',
        Saturday: 'Sábado',
        Sunday: 'Domingo',
    }
};

interface LanguageContextType {
    language: Language;
    toggleLanguage: () => void;
    t: (key: keyof typeof translations.EN) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
    const [language, setLanguage] = useState<Language>('EN');

    const toggleLanguage = () => {
        setLanguage(prevLang => prevLang === 'EN' ? 'PT' : 'EN');
    };

    const t = (key: keyof typeof translations.EN): string => {
        return translations[language][key] || translations['EN'][key] || key;
    };
    
    return (
        <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
